spring:
  application:
    name: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/appsdeveloperblog
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8081

# String props
jwt:
  auth:
    converter:
      resource-id: photo-app-code-flow-client
      principle-attribute: preferred_username
